# Generated by Django 4.2.6 on 2023-10-24 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Ads", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvServerInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accepted_ads", models.ManyToManyField(to="Ads.advertiser")),
            ],
        ),
        migrations.CreateModel(
            name="Servers",
            fields=[
                ("owner", models.IntegerField()),
                ("guild", models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel_name", models.CharField(max_length=100)),
                ("ad_frequency", models.IntegerField()),
                ("ad_last_shown", models.DateTimeField()),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channels",
                        to="ServerOwner.advserverinfo",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="advserverinfo",
            name="server",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="ServerOwner.servers"
            ),
        ),
    ]
