# Generated by Django 4.2.6 on 2023-10-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ServerOwner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="advserverinfo",
            name="current_cpm",
            field=models.FloatField(default=0),
        ),
    ]
