# Generated by Django 4.2.6 on 2023-10-25 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ServerOwner", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyIncome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("amount", models.FloatField()),
                (
                    "adv_server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_incomes",
                        to="ServerOwner.advserverinfo",
                    ),
                ),
            ],
        ),
    ]
