# Generated by Django 4.2.6 on 2023-10-29 16:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("Ads", "0003_alter_ad_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel_pk", models.IntegerField()),
                ("server_id", models.IntegerField()),
                ("time", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "ad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="live_instances",
                        to="Ads.ad",
                    ),
                ),
            ],
        ),
    ]
